#!/bin/vbash
# shellcheck disable=all

set firewall zone LOCAL description 'Local router zone'
set firewall zone LOCAL local-zone
set firewall zone LOCAL default-action 'drop'
set firewall zone LOCAL from LAN1 firewall name 'LAN1-LOCAL'
set firewall zone LOCAL from IOT firewall name 'IOT-LOCAL'
set firewall zone LOCAL from SERVER firewall name 'SERVER-LOCAL'
set firewall zone LOCAL from GUEST firewall name 'GUEST-LOCAL'
set firewall zone LOCAL from CONTAINERS firewall name 'CONTAINERS-LOCAL'
set firewall zone LOCAL from WIREGUARD firewall name 'WIREGUARD-LOCAL'
set firewall zone LOCAL from WAN firewall name 'WAN-LOCAL'

set firewall zone LAN1 description 'LAN1 zone'
set firewall zone LAN1 interface 'eth1'
set firewall zone LAN1 default-action 'drop'
set firewall zone LAN1 from LOCAL firewall name 'LOCAL-LAN1'
set firewall zone LAN1 from IOT firewall name 'IOT-LAN1'
set firewall zone LAN1 from SERVER firewall name 'SERVER-LAN1'
set firewall zone LAN1 from GUEST firewall name 'GUEST-LAN1'
set firewall zone LAN1 from CONTAINERS firewall name 'CONTAINERS-LAN1'
set firewall zone LAN1 from WIREGUARD firewall name 'WIREGUARD-LAN1'
set firewall zone LAN1 from WAN firewall name 'WAN-LAN1'

set firewall zone IOT description 'IOT VLAN zone'
set firewall zone IOT interface 'eth1.69'
set firewall zone IOT default-action 'drop'
set firewall zone IOT from LOCAL firewall name 'LOCAL-IOT'
set firewall zone IOT from LAN1 firewall name 'LAN1-IOT'
set firewall zone IOT from SERVER firewall name 'SERVER-IOT'
set firewall zone IOT from GUEST firewall name 'GUEST-IOT'
set firewall zone IOT from CONTAINERS firewall name 'CONTAINERS-IOT'
set firewall zone IOT from WIREGUARD firewall name 'WIREGUARD-IOT'
set firewall zone IOT from WAN firewall name 'WAN-IOT'

set firewall zone SERVER description 'SERVER VLAN zone'
set firewall zone SERVER interface 'eth1.200'
set firewall zone SERVER default-action 'drop'
set firewall zone SERVER from LOCAL firewall name 'LOCAL-SERVER'
set firewall zone SERVER from LAN1 firewall name 'LAN1-SERVER'
set firewall zone SERVER from IOT firewall name 'IOT-SERVER'
set firewall zone SERVER from GUEST firewall name 'GUEST-SERVER'
set firewall zone SERVER from CONTAINERS firewall name 'CONTAINERS-SERVER'
set firewall zone SERVER from WIREGUARD firewall name 'WIREGUARD-SERVER'
set firewall zone SERVER from WAN firewall name 'WAN-SERVER'

set firewall zone GUEST description 'GUEST VLAN zone'
set firewall zone GUEST interface 'eth1.250'
set firewall zone GUEST default-action 'drop'
set firewall zone GUEST from LOCAL firewall name 'LOCAL-GUEST'
set firewall zone GUEST from LAN1 firewall name 'LAN1-GUEST'
set firewall zone GUEST from IOT firewall name 'IOT-GUEST'
set firewall zone GUEST from SERVER firewall name 'SERVER-GUEST'
set firewall zone GUEST from CONTAINERS firewall name 'CONTAINERS-GUEST'
set firewall zone GUEST from WIREGUARD firewall name 'WIREGUARD-GUEST'
set firewall zone GUEST from WAN firewall name 'WAN-GUEST'

set firewall zone CONTAINERS description 'CONTAINERS zone'
set firewall zone CONTAINERS interface 'pod-CONTAINERS'
set firewall zone CONTAINERS default-action 'drop'
set firewall zone CONTAINERS from LOCAL firewall name 'LOCAL-CONTAINERS'
set firewall zone CONTAINERS from LAN1 firewall name 'LAN1-CONTAINERS'
set firewall zone CONTAINERS from IOT firewall name 'IOT-CONTAINERS'
set firewall zone CONTAINERS from SERVER firewall name 'SERVER-CONTAINERS'
set firewall zone CONTAINERS from GUEST firewall name 'GUEST-CONTAINERS'
set firewall zone CONTAINERS from WIREGUARD firewall name 'WIREGUARD-CONTAINERS'
set firewall zone CONTAINERS from WAN firewall name 'WAN-CONTAINERS'

set firewall zone WIREGUARD description 'WIREGUARD zone'
set firewall zone WIREGUARD interface 'wg0'
set firewall zone WIREGUARD default-action 'drop'
set firewall zone WIREGUARD from LOCAL firewall name 'LOCAL-WIREGUARD'
set firewall zone WIREGUARD from LAN1 firewall name 'LAN1-WIREGUARD'
set firewall zone WIREGUARD from IOT firewall name 'IOT-WIREGUARD'
set firewall zone WIREGUARD from SERVER firewall name 'SERVER-WIREGUARD'
set firewall zone WIREGUARD from GUEST firewall name 'GUEST-WIREGUARD'
set firewall zone WIREGUARD from CONTAINERS firewall name 'CONTAINERS-WIREGUARD'
set firewall zone WIREGUARD from WAN firewall name 'WAN-WIREGUARD'

set firewall zone WAN description 'WAN zone'
set firewall zone WAN interface 'eth0'
set firewall zone WAN default-action 'drop'
set firewall zone WAN from LOCAL firewall name 'LOCAL-WAN'
set firewall zone WAN from LAN1 firewall name 'LAN1-WAN'
set firewall zone WAN from IOT firewall name 'IOT-WAN'
set firewall zone WAN from SERVER firewall name 'SERVER-WAN'
set firewall zone WAN from GUEST firewall name 'GUEST-WAN'
set firewall zone WAN from CONTAINERS firewall name 'CONTAINERS-WAN'
set firewall zone WAN from WIREGUARD firewall name 'WIREGUARD-WAN'
